language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run lint

before_deploy:
  - npm run build
deploy:
  provider: npm
  email: kuitos.lau@gmail.com
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
