name: 叮咚买菜-签到176
rule:
  hour: 2
  minute: 0
  dayOfWeek: [0, 1, 2, 3, 4, 5, 6]
api:
  url: https://ddxq.mobi/api/v2/user/sign/
  method: post
  config:
    headers:
      host: ddxq.mobi
      origin: https://maicai.m.ddxq.mobi
      content-type: application/x-www-form-urlencoded
      cookie: $dd-176-sign-cookie
      x-requested-with: com.yaya.zone
    data:
      api_version: 8.6.0
      app_client_id: 3
      latitude: 0
      longitude: 0
      station_id:
